// <auto-generated />
using LocalBuisinessApi.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace LocalBuisinessApi.Migrations
{
    [DbContext(typeof(LocalBuisinessApiContext))]
    partial class LocalBuisinessApiContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("LocalBuisinessApi.Models.Restaurant", b =>
                {
                    b.Property<int>("RestaurantId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200) CHARACTER SET utf8mb4");

                    b.Property<string>("Cuisine")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100) CHARACTER SET utf8mb4");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50) CHARACTER SET utf8mb4");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.HasKey("RestaurantId");

                    b.ToTable("Restaurants");

                    b.HasData(
                        new
                        {
                            RestaurantId = 1,
                            Address = "123 Fake Ave, Portland, OR",
                            Cuisine = "Pizza",
                            Name = "Andy's Pizzeria",
                            Rating = 3
                        },
                        new
                        {
                            RestaurantId = 2,
                            Address = "456 Fake Ave, Portland, OR",
                            Cuisine = "Coffee/Pastries",
                            Name = "Hot Sips Cafe",
                            Rating = 4
                        },
                        new
                        {
                            RestaurantId = 3,
                            Address = "789 Fake Ave, Portland, OR",
                            Cuisine = "Burgers",
                            Name = "Rob's Burgers",
                            Rating = 5
                        });
                });

            modelBuilder.Entity("LocalBuisinessApi.Models.Shop", b =>
                {
                    b.Property<int>("ShopId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200) CHARACTER SET utf8mb4");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50) CHARACTER SET utf8mb4");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.Property<string>("Specialty")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100) CHARACTER SET utf8mb4");

                    b.HasKey("ShopId");

                    b.ToTable("Shops");

                    b.HasData(
                        new
                        {
                            ShopId = 1,
                            Address = "123 Fake St, Seattle, WA",
                            Name = "You can glue it!",
                            Rating = 5,
                            Specialty = "Crafts"
                        },
                        new
                        {
                            ShopId = 2,
                            Address = "123 Fake St, Seattle, WA",
                            Name = "Danny's Grocery Store",
                            Rating = 1,
                            Specialty = "Groceries"
                        },
                        new
                        {
                            ShopId = 3,
                            Address = "123 Fake St, Seattle, WA",
                            Name = "Jewelry Plus",
                            Rating = 2,
                            Specialty = "Jewelry"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
